In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
df = pd.read_json(  "Dataset for Detection of Cyber-Trolls.json" , lines= True,orient='columns')
df
df['annotation'][0]['label'][0] =int (df['annotation'][0]['label'][0])

df

,content,annotation,extras
0,Get fucking real dude.,"{'notes': '', 'label': [1]}",NaN
1,She is as dirty as they come and that crook ...,"{'notes': '', 'label': ['1']}",NaN
2,why did you fuck it up. I could do it all day...,"{'notes': '', 'label': ['1']}",NaN
3,Dude they dont finish enclosing the fucking s...,"{'notes': '', 'label': ['1']}",NaN
4,WTF are you talking about Men? No men thats n...,"{'notes': '', 'label': ['1']}",NaN
...,...,...,...
19996,I dont. But what is complaining about it goi...,"{'notes': '', 'label': ['0']}",NaN
19997,Bahah yeah i&;m totally just gonna&; get pis...,"{'notes': '', 'label': ['0']}",NaN
19998,hahahahaha >:) im evil mwahahahahahahahahaha,"{'notes': '', 'label': ['0']}",NaN
19999,What&;s something unique about Ohio? :),"{'notes': '', 'label': ['0']}",NaN
20000,Who is the biggest gossiper you know?,"{'notes': '', 'label': ['0']}",NaN

In [66]:
import pandas as pd

# Load the JSON file
df = pd.read_json("Dataset for Detection of Cyber-Trolls.json", lines=True, orient='columns')

def extract_label(annotation):
        return int(annotation['label'][0])  
df['label'] = df['annotation'].apply(extract_label)

df.head(10000)
df.drop("annotation", inplace = True, axis =1)
df.drop("extras", inplace = True, axis =1)

df.to_csv('dataset.csv')
df

                                                 content  label
0                                 Get fucking real dude.      1
1       She is as dirty as they come  and that crook ...      1
2       why did you fuck it up. I could do it all day...      1
3       Dude they dont finish enclosing the fucking s...      1
4       WTF are you talking about Men? No men thats n...      1
...                                                  ...    ...
19996    I dont. But what is complaining about it goi...      0
19997   Bahah  yeah i&;m totally just gonna&; get pis...      0
19998       hahahahaha >:) im evil mwahahahahahahahahaha      0
19999            What&;s something unique about Ohio? :)      0
20000              Who is the biggest gossiper you know?      0

[20001 rows x 2 columns]